// Generated by CoffeeScript 1.9.1
(function() {
  $("[data-func='radio']").click(function() {
    return window.open($(this).attr("data-url"), $(this).attr("data-name"), "height=650, width=360");
  });

}).call(this);

//# sourceMappingURL=common.js.map
